import { build } from 'esbuild';
import { builtinModules } from 'node:module';
import { mkdir, readFile, readdir, writeFile, copyFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const repo = fileURLToPath(new URL('../', import.meta.url));
const plugin = join(repo, 'plugins/x-plugin');
await mkdir(join(plugin, 'runtime'), { recursive: true });
const result = await build({
  absWorkingDir: repo,
  entryPoints: ['src/cli.ts'],
  outfile: 'plugins/x-plugin/runtime/x-plugin.cjs',
  bundle: true,
  platform: 'node',
  format: 'cjs',
  target: 'node24',
  minify: true,
  legalComments: 'inline',
  metafile: true,
  banner: {
    js: '// Generated by npm run build:plugin. Do not edit.\nif (Number(process.versions.node.split(".")[0]) < 24) { console.error("X Plugin requires Node.js 24 or newer."); process.exit(1); }',
  },
});
// Fail the build if an npm dependency would still be needed on the user's machine.
for (const output of Object.values(result.metafile.outputs)) {
  for (const entry of output.imports) {
    if (entry.external && !builtinModules.includes(entry.path.replace(/^node:/, '')))
      throw new Error(`Unbundled dependency: ${entry.path}`);
  }
}

// Ship full license/notice files for every package contributing to the bundle.
const packages = new Map();
for (const input of Object.keys(result.metafile.inputs)) {
  if (!input.startsWith('node_modules/')) continue;
  let dir = dirname(resolve(repo, input));
  while (dir !== repo) {
    try {
      const pkg = JSON.parse(await readFile(join(dir, 'package.json'), 'utf8'));
      if (pkg.name && pkg.version) {
        packages.set(pkg.name, { dir, pkg });
        break;
      }
    } catch (error) {
      if (error.code !== 'ENOENT') throw error;
    }
    dir = dirname(dir);
  }
}
const notices = [
  '# Bundled dependency notices\n\nGenerated from the locked dependencies by npm run build:plugin.\n',
];
for (const [name, { dir, pkg }] of [...packages].sort(([a], [b]) => a.localeCompare(b, 'en'))) {
  const files = (await readdir(dir))
    .filter((name) => /^(licen[cs]e|notice|copying)(\.|$)/i.test(name))
    .sort();
  if (!files.length) throw new Error(`Missing license text for ${name}`);
  notices.push(`\n## ${name}@${pkg.version}\n`);
  for (const file of files)
    notices.push(`\n### ${file}\n\n${await readFile(join(dir, file), 'utf8')}\n`);
}
await writeFile(join(plugin, 'THIRD_PARTY_NOTICES.md'), notices.join(''));
await copyFile(join(repo, 'LICENSE'), join(plugin, 'LICENSE'));
